name: Spring Boot CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  build-and-run:

    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: get java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Make maven wrapper executable
        run: chmod +x mvnw

      - name: Build and Test
        run: ./mvnw -B verify